-- MySQL Script generated by MySQL Workbench
-- ter 08 mar 2022 10:45:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zoologico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zoologico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zoologico` ;
USE `zoologico` ;

-- -----------------------------------------------------
-- Table `zoologico`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`especie` (
  `especie_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`especie_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoologico`.`sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`sexo` (
  `sexo_id` INT NOT NULL AUTO_INCREMENT,
  `sexo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`sexo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoologico`.`localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`localizacao` (
  `localizacao_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`localizacao_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoologico`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`animal` (
  `animal_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `especie_id` INT NOT NULL,
  `sexo_id` INT NOT NULL,
  `idade` INT NOT NULL,
  `localizacao_id` INT NOT NULL,
  PRIMARY KEY (`animal_id`),
  INDEX `especie_id_idx` (`especie_id` ASC) VISIBLE,
  INDEX `sexo_id_idx` (`sexo_id` ASC) VISIBLE,
  INDEX `localizacao_id_idx` (`localizacao_id` ASC) VISIBLE,
  CONSTRAINT `especie_id`
    FOREIGN KEY (`especie_id`)
    REFERENCES `zoologico`.`especie` (`especie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sexo_id`
    FOREIGN KEY (`sexo_id`)
    REFERENCES `zoologico`.`sexo` (`sexo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `localizacao_id`
    FOREIGN KEY (`localizacao_id`)
    REFERENCES `zoologico`.`localizacao` (`localizacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoologico`.`gerentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`gerentes` (
  `gerente_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`gerente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoologico`.`cuidadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`cuidadores` (
  `cuidador_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `gerente_id` INT NOT NULL,
  PRIMARY KEY (`cuidador_id`),
  INDEX `gerente_id_idx` (`gerente_id` ASC) VISIBLE,
  CONSTRAINT `gerente_id`
    FOREIGN KEY (`gerente_id`)
    REFERENCES `zoologico`.`gerentes` (`gerente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoologico`.`cuidador_animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoologico`.`cuidador_animal` (
  `cuidador_id` INT NOT NULL,
  `animal_id` INT NOT NULL,
  INDEX `cuidador_id_idx` (`cuidador_id` ASC) VISIBLE,
  INDEX `animal_id_idx` (`animal_id` ASC) VISIBLE,
  CONSTRAINT `cuidador_id`
    FOREIGN KEY (`cuidador_id`)
    REFERENCES `zoologico`.`cuidadores` (`cuidador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `animal_id`
    FOREIGN KEY (`animal_id`)
    REFERENCES `zoologico`.`animal` (`animal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
